libname project1 "your Path";

/*1.*/
proc import datafile= "path where csv file is located"
			out=project1.Computer_info 
			dbms=csv
			replace;
run;
proc print data=project1.Computer_info ;
run;

/*2.List all records for which source is S? Give the count for these records*/
proc print data= project1.Computer_info N="count=";
where  Order_Source="S";
run;


/*count using proc sql*/
proc sql;
select count(*) as count_order_source_S from 
project1.Computer_info
where Order_Source="S";
run;
quit;

/*3.	List the top three customers? What is the highest amount paid by them?*/


proc means data=project1.Computer_info max nway noprint;
var revenue;
class 	Customer_Number;
output out=top_three sum=sum_revenue max=Maximum_amt;
run;
proc print data= top_three;
run;

proc sort data=top_three;
by descending sum_revenue;
run;
proc print data= top_three(obs=3);
run;

/*using proc sql*/
proc sql outobs=3;
select Customer_Number,sum(revenue)	as sum_rev,max(revenue) as Max
from project1.Computer_info
group by Customer_Number
order by sum_rev desc;
quit;


/*4.Find the total revenue for the month of April?*/

proc means data=project1.Computer_info sum;
var revenue;
where month(Invoice_Date)=4;
run;

/*using proc sql*/
proc sql;
select sum(revenue) as sum_revenue_April
from project1.Computer_info
where month(Invoice_Date) =4;
quit;

/*5.Which representative is the best among the listed?*/
proc means data=project1.Computer_info nway sum noprint;
var revenue;
class Rep_Code;
output out=repre_reve(keep=Rep_Code sum_revenue_rep) sum=sum_revenue_rep;
run;
proc print data=repre_reve;
run;

proc sort data=repre_reve;
by descending sum_revenue_rep;
run;
proc print data= repre_reve(obs=1);
run;

/*using proc sql*/
proc sql outobs=1;
select Rep_Code,sum(revenue) as sum_rev
from project1.Computer_info
group by Rep_Code
order by sum_rev desc;
quit;

/*6.Which are the highest revenue collecting product and the lowest revenue collecting product?*/

proc means data =project1.Computer_info sum nway noprint;
var revenue;
class  Product_Code;
output out=sum_reve(keep=Product_Code sum_rev_prod_cod) sum=sum_rev_prod_cod;
run;
proc print data= sum_reve;
run;
proc sort data=	sum_reve;
by descending  sum_rev_prod_cod;
run;

data highest_lowest;
set sum_reve end=eof;
if _n_=1 or eof;
run;
proc print data= highest_lowest;
run;


/*using proc sql*/
proc sql;
create table prod_code as
select Product_Code,sum(revenue) as  sum_rev
from project1.Computer_info
group by Product_Code
order by sum_rev desc;
select * from prod_code;
quit;

/*7.	Which segments of people buy more computer peripherals?*/

proc means data=project1.Computer_info nway noprint;
var quantity;
class segment;
output out=qunatity_per_seg sum=sum_qunatity;
run;
proc print data= qunatity_per_seg;
run;
proc sort data=	qunatity_per_seg(keep=segment sum_qunatity) out=sorted;
by 	descending sum_qunatity;
run;
proc print data=sorted;
run;

/*using sql*/
proc sql ;
select segment,sum(quantity) as sum_quantity
from project1.Computer_info
group by segment
order by  sum_quantity desc;
quit;

/*8.-----------	Which product is bought more by each segment?*/

proc means data=project1.Computer_info nway noprint;
var quantity;
class  segment subseries;
output out=seg_prod_quant sum=sum_quant;
run;
proc sort data= seg_prod_quant out=sorted;
by segment  descending sum_quant;
run;
proc print data=sorted;
run;

/*9.Which are the products which have generated revenue of less than 100000?*/
proc sql;
select product_code,sum(revenue) as total_revenue
from  project1.Computer_info
group by product_code
having sum(revenue)<100000;
quit;

/*10. Which is the product which gets sold in maximum quantity?*/

proc sql outobs=1;
select product_code,sum(quantity) as total_sell
from project1.Computer_info
group by product_code
order by total_sell desc;
quit;

/*11.--------- Give the revenue generated by each brand for each quarter of the year 2009?*/

proc sql;
select brand,qtr(order_date)as Quarter,sum(revenue) as Brand_revenue
from  project1.Computer_info
group by brand,qtr(order_date)
order by Brand_revenue;
quit;

/*2nd mtd*/
data order_date_2009;
set  project1.Computer_info;
where year(order_date)=2009;
Quarter=qtr(order_date);
run;
proc print data= order_date_2009;
run;

proc report data=order_date_2009 nowd headskip headline;
column brand Quarter revenue;
define brand/group width=5;
define quarter/group;
run;

/*12.	 What is the revenue generated by each segment?*/
proc sql ;
select segment, sum(revenue) as total
from  project1.Computer_info
group by segment;
quit;


